### PR TITLE
Use `typo3` cli endpoint instead of `cli_dispatch.phpsh` 

### PR DESCRIPTION
**Pull request by YKWeyer**
Fixes https://github.com/in2code-de/in2publish_core/issues/53

I tested it on my typo3 setup (8.7.20), and I would appreciate if someone could review this MR as I have very little experience with typo3 :)

### CODE REVIEW

**Comment by YKWeyer** [comment]
Hi, I would love to have some feedback on this MR.
Is something missing? Is the use-case perhaps not clear? Should I target the `master` branch instead of `develop`? 

Please let me know what I can do to help having those improvements merged :wink:

**Comment by sbusemann** [comment]
@YKWeyer we will take a look at our next sprint (~Start of Feb)

**Comment by YKWeyer** [comment]
> @YKWeyer we will take a look at our next sprint (~Start of Feb)

Wonderful! Please let me know if I can be of any help :slightly_smiling_face:

**Comment by YKWeyer** [comment]
@sbusemann I noticed you implemented the code in the MR in the version 8.0 of the plugin :tada: 

There are still a couple of minor differences in the Readme and in the comments, you might want to have a closer look on those for consistency :wink: 
Feel free to close the MR once it isn't needed anymore

**Comment by vertexvaar** [comment]
Hi @YKWeyer,

Sorry that your actual PR was not included in the repo. It was overlooked during the upgrade phase.
I greatly appreciate your efforts and invite you to join the development again. I will personally check and merge your PRs :wink:

With Regards

**Pull request closed without merging**
